INSERT INTO BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('101', 'First Book', 'First Author', '30000');
INSERT INTO BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('201', 'Second Book', 'Second Author', '20000');
INSERT INTO BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('301', 'Third Book', 'Third Author', '15000');
INSERT INTO BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('401', 'Fourth Book', 'Fourth Author', '25000');
INSERT INTO BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('504', 'Fifth Book', 'Fifth Author', '80000');
INSERT INTO BOOK (ID, BOOK_TITLE, BOOK_AUTHOR, BOOK_PRICE) VALUES ('601', 'Sixth Book', 'Sixth Author', '50000');